name: Scrape Talk Locations

on: push

permissions:
  contents: write  # <-- This gives the token permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}  # You must set this secret in your repo settings
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/EvenStarArwen/mingyuhuang.github.io.git HEAD:master
